# Generated by Django 5.1.5 on 2025-02-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='user', max_length=50, null=True),
        ),
    ]
